#服务器
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    protocol-header-https-value: https
    protocol-header: X-Forwarded-Proto



spring:
  #数据库
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    slave1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456

  #redis
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0
  redis:
    host: redis1.coralglobal.cn
    port: 5379
    password: P7MG3pmymcMIRvNsi4jM
    database: 0

  #mq
  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /dev
#    publisher-confirm-type: correlated  #消息发送确认回调
#    listener:
#      simple:
#        acknowledge-mode: manual #消费者手动确认
#    publisher-returns: true  #回退模式
    host: rabbitmq2.coralgolbal.com
    port: 5672
    username: admin
    password: cg123456
    virtual-host: /dev
    publisher-confirm-type: correlated  #消息发送确认回调
    publisher-returns: true #回退模式

  #mongodb
  mongodb:
#    host: localhost
#    port: 27017
#    database: test
    uri: mongodb://mongodb.coralgolbal.com:27017/cg
   #uri: mongodb://admin:E7hmLq0mnweks4tyxL0I@172.16.100.63:27017,172.16.100.64:27017,172.16.100.65:27017/notice?authSource=admin&authMechanism=SCRAM-SHA-1


#单数据源可以这样配置，多数据源需要专门的配置文件配置
#mybatis:
#  mapper-location: classpath*:mapper/*.xml



#自定义属性配置
custom:
  #值
  value: 建文帝
  #对象
  person:
    name: chenjianwen
    age: 18
  #数组
  arr: [1,2,3]
  #list
  list:
    - 110
    - 119
    - 112
  #map
  map: {key1: value1,key2: value2}
  #list中包含map
  listMap:
    - {list1: map1,list2: map2}
    - {a: b,c: d}


